### ISSUE TITLE
投げ銭機能がない

### ISSUE THREAD

**Issue by IkkoKojima** [IkkoKojima/lets-go-zoo#6]
収入源の1つとなるとなる投げ銭(寄付・ドネート)機能がない。

以下の2種類の投げ銭を用意したい
- コロナで困っている動物園への投げ銭
  - stripeに3.6% 製作者に16.4% 動物園や水族館に80%
    - 500円(内訳 : 18 + 82 + 400)
- 製作者への援助
  - stripeに3.6% 製作者に96.4%
    - 500円(内訳 : 18 + 482)

収入源となるだけでなく、社会にも貢献できる可能性があるため、ぜひ実装したい

**Comment by IkkoKojima** [comment]
こんな感じでUIを作った。が、バグがある...

- リダイレクト(Link)時に全コンテンツが描画されない #13 と同一と思われる
- 決済画面に遷移しない
  - PKeyが読み込めない模様。Netlify環境変数の読み方が違うのかな...?

```:error
Uncaught (in promise) IntegrationError: Please call Stripe() with your publishable key. You used an empty string.
    at new t (https://js.stripe.com/v3:1:10981)
    at new e (https://js.stripe.com/v3:1:151032)
    at Cu (https://js.stripe.com/v3:1:164439)
    at u (https://d33wubrfki0l68.cloudfront.net/bundles/a72bdf3dc0ed45c88bb2d08f37acb0339873cf5e.js:1:746564)
    at https://d33wubrfki0l68.cloudfront.net/bundles/a72bdf3dc0ed45c88bb2d08f37acb0339873cf5e.js:1:746913
```

**Comment by IkkoKojima** [comment]
margeの差し戻しは、リリース前のため不要。

**Comment by IkkoKojima** [comment]
https://community.netlify.com/t/common-issue-using-environment-variables-on-netlify-correctly/267/14

公式ドキュメントからはここを見ろとリンクされているが、どのやり方を使えば良いのかわからん...

そもそも、フロントエンドで環境変数って使えないのか!?そんなまさかねぇ...?

**Comment by IkkoKojima** [comment]
そもそも、ビルド後はHTMLになるから隠すの無理か？

何か方法はないのかなぁ

**Comment by IkkoKojima** [comment]
API Keyのうち、`Publishable`な方は、明確に「JavaScriptなどで安全に公開できます」と公式ドキュメントに書いてある。

https://stripe.com/docs/keys

一方でSKUのIDだが、こちらは公開して良いのか不明。
ただ、サンプルコードで堂々と公開しているということは、問題ないということか...?

**Comment by IkkoKojima** [comment]
OK,ベタガキなら動いた

細かい文言などの修正はやりたいが、別チケットで
